name = "sqlight"
version = "0.2.0"
licences = ["Apache-2.0"]
description = "Use SQLite from Gleam!"

repository = { type = "github", user = "lpil", repo = "sqlight" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.25"
esqlite = "~> 0.8"

[dev-dependencies]
gleeunit = "~> 0.7"
